# Generated by Django 5.2.5 on 2025-08-27 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Username')),
                ('phone_number', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(db_index=True, max_length=200, unique=True, verbose_name='Email')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Birth Date')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Is Teacher')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Is Employee')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
