# Generated by Django 5.2.5 on 2025-09-01 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='Device ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Name')),
                ('pulse_to_liter', models.FloatField(default=650.0, verbose_name='Pulse to Liter')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('count', models.PositiveIntegerField(verbose_name='Pulse Count')),
                ('liters', models.FloatField(editable=False, verbose_name='Liters')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='water.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Water Log',
                'verbose_name_plural': 'Water Logs',
            },
        ),
    ]
